services:
  - type: web
    name: fashion-hub
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn djnew.wsgi"
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: "3.10.11"
    plan: free
